repository:
  url                       : https://github.com/johnson7543/PM2.5_analysis/blob/main/PM2.5.ipynb  # Online location of your book
  path_to_book              : PM2.5_analysis/PM2.5.ipynb   # Optional path to your book, relative to the repository root
  branch                    : master  # Which branch of the repository should be used when creating links (optional)
  
launch_buttons:
  notebook_interface: "jupyterlab"  # or "classic"
